# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b597f988b2c13031d79a5a95e8f5a05ea12869947c509a86b79b784b1ac10e15afc0b8ec36bf6b19ea517b89b2df6155904f18b1b7ba0135e6b2d97f19df24c9

test:
  secret_key_base: f11ccbfddad0c056a63459353edbcd75bd19706fae74c88a4906b63db8960719e6b723eecbde0b3cd3423a164ca7e5038dc5bde65ea84ac408ab4a337cd9d750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
